### ISSUE TITLE
Bug Report by Uncle LYHME - Cannot enable elements after they get disabled

### ISSUE THREAD

**Issue by Pustalorc** [Pustalorc/AutoTurnOff#3]
Provided description:
You have to pickup and replace down lights and sentries to get them working again.

**Comment by Pustalorc** [comment]
![image](https://user-images.githubusercontent.com/17557714/70925831-d9e79b00-2023-11ea-9e97-b13c8f2a58fe.png)
This was further provided to help patch the issue/test.

**Comment by Pustalorc** [comment]
Hopefully fixed with 8edc2c111d2a7171ebfa9e619f3cfe88523bc5a9. Check with the user.

**Comment by Cogitoergo** [comment]
Hi. The problem still exists with the latest build, exactly as described.

**Comment by Pustalorc** [comment]
If this still exists, this is an internal mistake on nelson's end, as this plugin no longer does its own steamcalls, but rather calls base game methods to modify the state. Please report it to nelson ONLY if you can confirm that it still happens when ONLY this plugin is installed. You can report it here: https://github.com/SmartlyDressedGames/Unturned-3.x-Community/issues
